# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QControl.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QControl(object):
    def setupUi(self, QControl):
        QControl.setObjectName("QControl")
        QControl.resize(800, 600)
        QControl.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(QControl)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 631, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("quality-control.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 510, 64, 19))
        self.label_2.setObjectName("label_2")
        QControl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QControl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menuQControl = QtWidgets.QMenu(self.menubar)
        self.menuQControl.setObjectName("menuQControl")
        self.menuMotors = QtWidgets.QMenu(self.menuQControl)
        self.menuMotors.setObjectName("menuMotors")
        self.menuHover = QtWidgets.QMenu(self.menuQControl)
        self.menuHover.setObjectName("menuHover")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuGraphic = QtWidgets.QMenu(self.menubar)
        self.menuGraphic.setObjectName("menuGraphic")
        QControl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QControl)
        self.statusbar.setObjectName("statusbar")
        QControl.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(QControl)
        self.toolBar.setObjectName("toolBar")
        QControl.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClose = QtWidgets.QAction(QControl)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/filequit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(QControl)
        self.actionAbout.setObjectName("actionAbout")
        self.actionScan = QtWidgets.QAction(QControl)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/thin_motor_electric-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScan.setIcon(icon1)
        self.actionScan.setObjectName("actionScan")
        self.actionMotors = QtWidgets.QAction(QControl)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/editzoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMotors.setIcon(icon2)
        self.actionMotors.setObjectName("actionMotors")
        self.actionNew = QtWidgets.QAction(QControl)
        self.actionNew.setObjectName("actionNew")
        self.actionLigntninbolt = QtWidgets.QAction(QControl)
        self.actionLigntninbolt.setObjectName("actionLigntninbolt")
        self.actionScan_2 = QtWidgets.QAction(QControl)
        self.actionScan_2.setObjectName("actionScan_2")
        self.menuMotors.addAction(self.actionScan)
        self.menuHover.addAction(self.actionScan_2)
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addSeparator()
        self.menuQControl.addAction(self.menuMotors.menuAction())
        self.menuQControl.addAction(self.menuHover.menuAction())
        self.menuInicio.addAction(self.actionClose)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSearch.addAction(self.actionMotors)
        self.menuSearch.addAction(self.actionLigntninbolt)
        self.menuGraphic.addAction(self.actionNew)
        self.menubar.addAction(self.menuInicio.menuAction())
        self.menubar.addAction(self.menuQControl.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuGraphic.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionClose)
        self.toolBar.addAction(self.actionScan)
        self.toolBar.addAction(self.actionMotors)

        self.retranslateUi(QControl)
        QtCore.QMetaObject.connectSlotsByName(QControl)

    def retranslateUi(self, QControl):
        _translate = QtCore.QCoreApplication.translate
        QControl.setWindowTitle(_translate("QControl", "Quality Control"))
        self.label_2.setText(_translate("QControl", "TextLabel"))
        self.menuQControl.setTitle(_translate("QControl", "QControl"))
        self.menuMotors.setTitle(_translate("QControl", "Motors"))
        self.menuHover.setTitle(_translate("QControl", "Hover"))
        self.menuInicio.setTitle(_translate("QControl", "Inicio"))
        self.menuAbout.setTitle(_translate("QControl", "Help"))
        self.menuSearch.setTitle(_translate("QControl", "Search"))
        self.menuGraphic.setTitle(_translate("QControl", "Graphic"))
        self.toolBar.setWindowTitle(_translate("QControl", "toolBar"))
        self.actionClose.setText(_translate("QControl", "Exit"))
        self.actionAbout.setText(_translate("QControl", "About"))
        self.actionScan.setText(_translate("QControl", "Scan"))
        self.actionMotors.setText(_translate("QControl", "SMotors"))
        self.actionNew.setText(_translate("QControl", "New"))
        self.actionLigntninbolt.setText(_translate("QControl", "Ligntninbolt"))
        self.actionScan_2.setText(_translate("QControl", "Scan"))
import recursos_1_rc
